### PR TITLE
Access to language's name for itself

### PR DESCRIPTION
**Pull request by hosford42**
I modified the code to allow the use of the language's own name for itself, in addition to the English name for it. I need the functionality for an NLP project I'm working on. I tried to preserve backwards compatibility as much as possible, to some extent at the expense of a clean and intuitive interface. If you don't care for the function/variable/key naming scheme I used, I am open to suggestions; I'm not picky about the specific interface.

### CODE REVIEW

**Comment by hosford42** [comment]
Oh no, these are French names, not self-referencing names, aren't they? Well, I suppose the code will work great if the table is changed.

**Comment by hosford42** [comment]
But who wants to do that?

**Comment by hosford42** [comment]
Okay, I don't know how comfortable you are going to be with it, but I built a new file with native language names instead of French names. I used a different name for the file to prevent confusion with the file distributed by the ISO organization. I used data from the Wikipedia article, [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), to populate the native names for the languages.

**Comment by janpipek** [comment]
Hi Aaron,
thanks for your pull request, native language seems like a good idea. However, let me give a look and thought before I accept it.

**Comment by hosford42** [comment]
Certainly! I know it can be uncomfortable to have other people rummaging around in your code, particularly when they have different aesthetic preferences. I'll be happy to revise the changes based on your feedback if you're unhappy with anything I've done.

**Comment by janpipek** [comment]
I think I will accept it - native language is nothing against the philosophy of this package. On the contrary, I welcome it. I am just afraid of breaking someone's working code. Till now, I spotted that I will have to add your renamed file to setup.py. Second issue is that your .txt contains a few more variants of language names (in English) -- it's not much convenient, but probably ok. Let me still think a bit :-)

**Comment by hosford42** [comment]
I can very easily set the English language names back to their original values, if you like.

**Comment by janpipek** [comment]
Merged because no other conflict / potential risk found :-)

**Comment by janpipek** [comment]
Now officially included in 0.1.3.

**Comment by hosford42** [comment]
I installed the latest version from the Python package index with pip and got an error when I tried to import it. It couldn't find the new text file. I verified it's not present in the source archive. The date on the source distribution currently available there is from 2016-06-03.

**Comment by janpipek** [comment]
0.1.4 fixes that.

**Comment by hosford42** [comment]
Everything checked out from my end this time. Thanks!

**Pull request merged**
